In [1]:
import pandas as pd

In [2]:
median_price_df = pd.read_csv('2017-2019_price.csv')
median_price_df.head()

,RegionName,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,...,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31
0,"New York, NY",386000.0,387000.0,387000.0,390333.0,395000.0,406667.0,420000.0,426667.0,425000.0,...,407500.0,407500.0,410833.0,421667.0,431667.0,435667.0,432333.0,425667.0,421667.0,420000.0
1,"Los Angeles-Long Beach-Anaheim, CA",571833.0,570167.0,577498.0,589165.0,602498.0,609667.0,615000.0,617917.0,619583.0,...,633167.0,643931.0,649098.0,653431.0,661000.0,662667.0,661667.0,654167.0,652667.0,654333.0
2,"Chicago, IL",211333.0,211333.0,216200.0,224867.0,234833.0,241800.0,243467.0,240900.0,233400.0,...,228667.0,236000.0,244000.0,249333.0,251000.0,249333.0,243333.0,238333.0,235000.0,234333.0
3,"Dallas-Fort Worth, TX",236500.0,239000.0,242333.0,249667.0,256667.0,261333.0,261643.0,259583.0,254917.0,...,259193.0,265823.0,272823.0,277355.0,280092.0,278425.0,274333.0,271667.0,270000.0,271833.0
4,"Philadelphia, PA",226333.0,221333.0,217667.0,222000.0,231000.0,243633.0,249300.0,250967.0,243000.0,...,231884.0,236584.0,245918.0,255000.0,262667.0,266633.0,260633.0,253300.0,248333.0,249000.0

In [3]:
df = median_price_df.set_index('RegionName')
df['2017']=None
df

,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,...,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2017
RegionName,,,,,,,,,,,,,,,,,,,,,
"New York, NY",386000.0,387000.0,387000.0,390333.0,395000.0,406667.0,420000.0,426667.0,425000.0,412333.0,...,407500.0,410833.0,421667.0,431667.0,435667.0,432333.0,425667.0,421667.0,420000.0,None
"Los Angeles-Long Beach-Anaheim, CA",571833.0,570167.0,577498.0,589165.0,602498.0,609667.0,615000.0,617917.0,619583.0,616250.0,...,643931.0,649098.0,653431.0,661000.0,662667.0,661667.0,654167.0,652667.0,654333.0,None
"Chicago, IL",211333.0,211333.0,216200.0,224867.0,234833.0,241800.0,243467.0,240900.0,233400.0,225733.0,...,236000.0,244000.0,249333.0,251000.0,249333.0,243333.0,238333.0,235000.0,234333.0,None
"Dallas-Fort Worth, TX",236500.0,239000.0,242333.0,249667.0,256667.0,261333.0,261643.0,259583.0,254917.0,252940.0,...,265823.0,272823.0,277355.0,280092.0,278425.0,274333.0,271667.0,270000.0,271833.0,None
"Philadelphia, PA",226333.0,221333.0,217667.0,222000.0,231000.0,243633.0,249300.0,250967.0,243000.0,236667.0,...,236584.0,245918.0,255000.0,262667.0,266633.0,260633.0,253300.0,248333.0,249000.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Daytona Beach, FL",174667.0,173000.0,174667.0,178333.0,181633.0,185633.0,188967.0,192233.0,192733.0,193067.0,...,215723.0,218057.0,223000.0,226333.0,225667.0,225333.0,225663.0,227327.0,227627.0,None
"Des Moines, IA",181667.0,179333.0,177867.0,178533.0,185200.0,193000.0,196333.0,197000.0,194000.0,197000.0,...,207333.0,213333.0,217333.0,218417.0,223417.0,219750.0,217750.0,215771.0,217431.0,None
"Provo, UT",258300.0,261633.0,262550.0,266584.0,269917.0,272460.0,274960.0,275432.0,276970.0,277470.0,...,310500.0,316000.0,322525.0,325275.0,326788.0,327930.0,331512.0,332330.0,333997.0,None
"Durham, NC",237667.0,240750.0,238583.0,244733.0,247317.0,256983.0,262667.0,265000.0,259167.0,258333.0,...,284250.0,287917.0,289917.0,290333.0,287167.0,285205.0,284538.0,291705.0,296333.0,None
"Fort Collins, CO",342650.0,345783.0,345783.0,347633.0,348333.0,351650.0,354983.0,355845.0,350331.0,353138.0,...,388133.0,393133.0,395225.0,396708.0,395042.0,391633.0,389167.0,385833.0,386667.0,None

In [4]:
avg = []
for x in range(len(df)):
    #print(df.iloc[x,1])
    #city_avg = []
    #for y in range(12):
        #city_avg.append(df_2017.iloc[x,y])
    avg.append(int((df.iloc[x, 1] + df.iloc[x, 2] + df.iloc[x, 3] + df.iloc[x, 4] + df.iloc[x, 5] + df.iloc[x, 6] + df.iloc[x, 7] + df.iloc[x, 8] + df.iloc[x, 9] + df.iloc[x, 10] + df.iloc[x, 11] + df.iloc[x, 12]) / 12))
df['2017']= avg
#avg
avg_2018 = []
for x in range(len(df)):
    #print(df.iloc[x,1])
    #city_avg = []
    #for y in range(12):
        #city_avg.append(df_2017.iloc[x,y])
    avg_2018.append(int((df.iloc[x, 13] + df.iloc[x, 14] + df.iloc[x, 15] + df.iloc[x, 16] + df.iloc[x, 17] + df.iloc[x, 18] + df.iloc[x, 19] + df.iloc[x, 20] + df.iloc[x, 21] + df.iloc[x, 22] + df.iloc[x, 23] + df.iloc[x, 24]) / 12))
df['2018']= avg_2018
avg_2019 = []
for x in range(len(df)):
    #print(df.iloc[x,1])
    #city_avg = []
    #for y in range(12):
        #city_avg.append(df_2017.iloc[x,y])
    avg_2019.append(int((df.iloc[x, 25] + df.iloc[x, 26] + df.iloc[x, 27] + df.iloc[x, 28] + df.iloc[x, 29] + df.iloc[x, 30] + df.iloc[x, 31] + df.iloc[x, 32] + df.iloc[x, 33] + df.iloc[x, 34] + df.iloc[x, 35] + df.iloc[x, 36]) / 12))
df['2019']= avg_2019

In [5]:
df

,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,...,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2017,2018,2019
RegionName,,,,,,,,,,,,,,,,,,,,,
"New York, NY",386000.0,387000.0,387000.0,390333.0,395000.0,406667.0,420000.0,426667.0,425000.0,412333.0,...,421667.0,431667.0,435667.0,432333.0,425667.0,421667.0,420000.0,404416,414097,419020
"Los Angeles-Long Beach-Anaheim, CA",571833.0,570167.0,577498.0,589165.0,602498.0,609667.0,615000.0,617917.0,619583.0,616250.0,...,653431.0,661000.0,662667.0,661667.0,654167.0,652667.0,654333.0,605312,640611,646689
"Chicago, IL",211333.0,211333.0,216200.0,224867.0,234833.0,241800.0,243467.0,240900.0,233400.0,225733.0,...,249333.0,251000.0,249333.0,243333.0,238333.0,235000.0,234333.0,228044,233166,238503
"Dallas-Fort Worth, TX",236500.0,239000.0,242333.0,249667.0,256667.0,261333.0,261643.0,259583.0,254917.0,252940.0,...,277355.0,280092.0,278425.0,274333.0,271667.0,270000.0,271833.0,252901,263851,269364
"Philadelphia, PA",226333.0,221333.0,217667.0,222000.0,231000.0,243633.0,249300.0,250967.0,243000.0,236667.0,...,255000.0,262667.0,266633.0,260633.0,253300.0,248333.0,249000.0,234019,239058,247939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Daytona Beach, FL",174667.0,173000.0,174667.0,178333.0,181633.0,185633.0,188967.0,192233.0,192733.0,193067.0,...,223000.0,226333.0,225667.0,225333.0,225663.0,227327.0,227627.0,186527,206338,219387
"Des Moines, IA",181667.0,179333.0,177867.0,178533.0,185200.0,193000.0,196333.0,197000.0,194000.0,197000.0,...,217333.0,218417.0,223417.0,219750.0,217750.0,215771.0,217431.0,190244,202523,211494
"Provo, UT",258300.0,261633.0,262550.0,266584.0,269917.0,272460.0,274960.0,275432.0,276970.0,277470.0,...,322525.0,325275.0,326788.0,327930.0,331512.0,332330.0,333997.0,272914,300699,317779
"Durham, NC",237667.0,240750.0,238583.0,244733.0,247317.0,256983.0,262667.0,265000.0,259167.0,258333.0,...,289917.0,290333.0,287167.0,285205.0,284538.0,291705.0,296333.0,255641,274868,284250
"Fort Collins, CO",342650.0,345783.0,345783.0,347633.0,348333.0,351650.0,354983.0,355845.0,350331.0,353138.0,...,395225.0,396708.0,395042.0,391633.0,389167.0,385833.0,386667.0,353237,381585,387414

In [9]:
df.drop(df.iloc[:, 0:6], inplace=True, axis=1)
df

                                      2017    2018    2019
RegionName
New York, NY                        404416  414097  419020
Los Angeles-Long Beach-Anaheim, CA  605312  640611  646689
Chicago, IL                         228044  233166  238503
Dallas-Fort Worth, TX               252901  263851  269364
Philadelphia, PA                    234019  239058  247939
...                                    ...     ...     ...
Daytona Beach, FL                   186527  206338  219387
Des Moines, IA                      190244  202523  211494
Provo, UT                           272914  300699  317779
Durham, NC                          255641  274868  284250
Fort Collins, CO                    353237  381585  387414

[94 rows x 3 columns]

In [10]:
df.to_csv('saleprice_2017_avg.csv')